### ISSUE TITLE
강사님 Tip

### ISSUE THREAD

**Issue by kikiru328** [kikiru328/enterprise_analysis#4]
**강사 왈: 차별화된 가치 --가 목적일 것이다. _'결과물로 가치를 만들어 내야 한다'_**
**SQL을 강조하시네 왜그러지**
**적합도 ? 머신러닝 모델의 검증 학습도 ; 머신 모델 적합도가 높다고 좋은게 아님 ; 일반화가 되지 않음. - 일반화 검사가 필수적으로 진행이 됨. => 적합도가 높으려면 전처리가 잘 되어야 함,**
_추천상품 알고리즘 (이거 꼭 해야되는건가?)_
_추천 알고리즘 ; surprise / 딥러닝 -auto encoding_ 
**외부데이터 : 크롤링을 통해서 기사/경제상황/경쟁사상황 등등을 가져와서 분석해봄. --> 인사이트를 창출**
**파생변수 : 내 외부 데이터를 포함한 파생변수를 만들면 좋긴 할거다. _지수 개발을 해야됨_**

_강사: 1. 기준 정보를 봄. 2. 고객의 패턴의 변화를 보여주는 지수를 개발함_
_시각화 : powerbi 등 다양한 시각화 자료를 활용해서 효율적으로 프로젝트를 보일 수 있도록_

**_발표 : 자료가 잘 만들어져야 함._**

**데이터 상세설명 제대로 보기**
_계열사  :  롯데 백화점/롯데마트/롯데슈퍼/롭스_
**구매내역정보가 핵심. 여기서 구매패턴을 파악할 수 있음-특히 상품관련**
**멤버십은 데이터가 부족, 참고정도**
**채널이용 - 이용횟수가 최대 3개월간의 모바일/app로그인 횟수/ 최근 3개월간의 온라인쇼핑몰 구매 횟수를 의미 (제한된 데이터를 어떻게 활용할 것 인지 파악)**

**Comment by pkwon35** [comment]
비정형화된 사람들의 의견 / 리뷰 등을 가지고와 감성분석을 진행한다.
하지만, 그에 그치지 않고, 분류된 긍정적 / 부정적 comment 들을 나눠서 세부적으로 들여다 봐야한다.

ex) 부정적인 글을 적은 사람들의 글을 보니 n가지 분류가능
1) 음식/상품 quality 대한 부정적인 글 : "맛없다" "너무짜다"
2) 서비스에 대한 부정적인 글 : "주차장 좁다" "시설 더럽다"
3) 가격관련 부정적인 글 : "너무 비싸다" "가성비 최악"

이처럼, 도메인 전문가들이 도메인+데이터분석능력 을 활용한 솔루션 제시가 중요하다.

**Comment by kikiru328** [comment]
데이터를 가지고 (매출분석)
issue finding (무엇이 문제가 되고 있는지)

**Comment by SeunghyeChae** [comment]
고객을 따로 나눠서 보면 X 
고객 통합 데이터를 가지고 issue finding 하기 
* 고객에 맞춘 마케팅이 대세이기 때문
