### ISSUE TITLE
features

### ISSUE THREAD

**Issue by kikiru328** [kikiru328/enterprise_analysis#7]
1. 제휴사
2. 영수증번호
3. 대분류코드
4. 중분류코드
5. 소분류코드
6. 고객번호
7. 점포코드
8. 구매일자
9. 구매시간
10. 구매금액

**Comment by pkwon35** [comment]
1. 고객 특성별 분류
    1.1 고객의 특성별 비율 확인
    1.2 제휴사별 고객 특성 확인 - 인사이트 뽑을 수 있을 듯 ( 타겟 )
    1.3 제휴사별 멤버십 사용 비율 - 인사이트 뽑을 수 있을 듯 (특정 멤버십이 사용되는 제휴사)
    1.4 멤버십과 매출액의 관계 - 멤버십 유/무에 따른 고객분류 ( 멤버십 추천 알고리즘 생성 )
    1.5 성별별 매출액 관계 - 광고 마케팅 제언 ( 중분류 기준 )
    1.6 지역별 점포 매출액 기준 - 점포별 영업 전략 비교
    1.7 연령대와 점포 매출액 비교 - 연령대별 소비액 차이 비교 ( 타겟 )
    1.8 연령대별 중분류 확인 - 패턴 찾을 수 있으면 좋을 듯
    1.9 유통채널과 고객 - 온라인 /오프라인 매출액 비교 (3개월치)
 
2. 고객 + 경쟁사별 분류
    2.1 고객 -경쟁사 이용 비율 비교 - 고객 유치 마케팅 제언 혹은 이탈 방지 마케팅 제언



등등 더 추가해야할 듯??
